//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_Veterinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int Id { get; set; }
        public string NombreEnfermedad { get; set; }
        public string FechaEnfermedad { get; set; }
        public int PacienteId { get; set; }
        public int VacunaId { get; set; }
    
        public virtual Vacuna Vacuna { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
